### ISSUE TITLE
Proposal for new rules file

### ISSUE THREAD

**Issue by samrocketman** [skippyPeanutButter/yaml_bot#22]
To make your rules file less verbose you can abstract ruby specific things into more generic concepts and then translate them into Ruby at runtime.  For instance, defining your types:

* Multitype vs a single type.  A multitype could be e.g. multiple types like a list or a map or a string for a single key.  The multitype could have some additional args with it.

When defining the other types; think more along the lines of the YAML spec (as opposed to ruby built-ins).  Other types include:

* Object (i.e. a Hash)
* List (Array)
* String (...)
* Number (int or double, etc)
* Boolean (TrueClass or FalseClass)

Other things to think about with a redesign of the spec: key dependencies.  Some keys may be dependent on other keys.  You should be able to specify when a key depends on another key (and when validating the other key use the other key's rules normally).

**Comment by samrocketman** [comment]
Types of existence:

1. One key or a different key (either or are okay but at least one of them must exist).
2. Other key must key exist (only a single type)
3. Optional keys may only require keys if the optional key exists.  In that case, the other key may or may not need to exist; but only if the optional key does exist.

# Case 3

Let's say `secrets_id` (which is a `String`) and `secrets` (which is a List of Hashes) are both keys that are optional in a YAML spec.  However, if `secrets` exists then `secrets_id` must exist because `secrets` depends on it.  With that in mind:

Valid (no content because both keys are optional):

```yaml
```

Valid (`secrets` key is optional):

```yaml
secrets_id: foo
```

Valid (both optional keys are present):

```yaml
secrets_id: foo
secrets:
  - ...
```

Not Valid (when the optional key `secrets` exists; `secrets_id` is a requirement):

```
secrets:
  - ...
```

**Comment by samrocketman** [comment]
```
foo:
  default_baz: hurdurr
  bar:
    - baz: durrhurr
      pizza:
        - large
```
For key `foo.bar[*].pizza`, relative to the `pizza` key: `baz` and `../../default_baz` are required.

**Comment by skippyPeanutButter** [comment]
yaml
```
language: go
jdk: oraclejdk7
install:
  - "sudo yum clean all"
  - "echo 'y' | android update sdk --no-ui --all --filter build-tools-23.0.3"
  - "sudo yum -y install glibc.i686 libz.so.1 libgcc libgcc_s.so.1"

script:
  - export tpsReleaseSigningStoreFile=${WORKSPACE}/keystore/tpsrelease.keystore.jks
  - export debugSigningStoreFile=${WORKSPACE}/keystore/test-release.keystore.jks
  - export prodReleaseSigningStoreFile=${WORKSPACE}/keystore/prodrelease.keystore.jks
  - export debugKeyPassword=xfhome
  - export debugStorePassword=xfhome
  - export debugKeyAlias=xfhrel
  - ./gradlew antHillBuild --info

jenkins:
  use_gerrit: false
  sudo: true
  collect:
    artifacts:
      - "**/App/build/**/*.apk"
      - "**/reports/tests/**/index.html"
```

Rules
```
root_keys:
  optional:
    - language:
        accepted_types:
          - String
        values:
          - 'android'
          - 'go'
          - 'python'
          - 'ruby'
    - before_install:
        accepted_types:
          - String
          - Array
    - install:
        accepted_types:
          - String
          - Array
    - before_script:
        accepted_types:
          - String
          - Array
    - script:
        accepted_types:
          - String
          - Array
    - branches:
        subkeys:
          optional:
            - only:
                accepted_types:
                  - Array
            - except:
                accepted_types:
                  - Array
    - jenkins:
        subkeys:
          optional:
            - stage:
                accepted_types:
                  - Array
            - sudo:
                accepted_types:
                  - TrueClass
                  - FalseClass
            - use_gerrit:
                accepted_types:
                  - TrueClass
                  - FalseClass
            - collect:
                subkeys:
                  optional:
                    - artifacts:
                        accepted_types:
                          - String
                          - Array
```

**Comment by samrocketman** [comment]
Generic rules definition.

```yaml
defaults:
  <default values for rules>
rules:
  - key: 'yaml address'
    required: true|false|optional
    and_requires: ['list of yaml addresses']
    or_requires: ['list of yaml addresses']
    value_whitelist: ['list of values']
    value_blacklist: ['list of values']
```

```yaml
defaults:
  required: optional
rules:
  - key:
```
